export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';
export const CREATE_TRANSACTIONS = 'CREATE_TRANSACTIONS';
export const READ_TRANSACTIONS = 'READ_TRANSACTIONS';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_CATEGORIES = 'CREATE_CATEGORIES';
export const READ_CATEGORIES = 'READ_CATEGORIES';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const CREATE_BUDGET = 'CREATE_BUDGET';
export const READ_BUDGETS = 'READ_BUDGETS';
export const UPDATE_BUDGET = 'UPDATE_BUDGET';
export const DELETE_BUDGET = 'DELETE_BUDGET';